version: '3'
services:
    db:
        container_name: c2-db
        build:

            context: ./docker/mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: admin
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MARIADB_ROOT_HOST: '%'
            MYSQL_ROOT_HOST: '%'
        networks:
            sia-network:
                ipv4_address: 172.20.0.6
        ports:
            - "3306:3306"
        expose:
            - 3306

    php-fpm:
        container_name: c2-php
        build:
            context: ./docker/php-fpm
            args:
                - INSTALL_XDEBUG=false
                - XDEBUG_REMOTE_HOST=127.0.0.1
                - XDEBUG_REMOTE_PORT=9000
                - XDEBUG_IDE_KEY=project
                - UID=1001
                - GID=1001
        volumes:
            - ./symfony:/var/www/symfony
        networks:
            sia-network:
                ipv4_address: 172.20.0.4
        working_dir: /var/www/symfony
        restart: unless-stopped
        expose:
            - 9001
        depends_on:
            - db

    nginx:
        container_name: c2-nginx
        build:
            context: ./docker/nginx
            args:
                - UID=1001
                - GID=1001
        volumes:
            - ./symfony:/var/www/symfony
        restart: unless-stopped
        networks:
            sia-network:
                ipv4_address: 172.20.0.7
        working_dir: /var/www/symfony
        depends_on:
            - php-fpm
        ports:
            - "80:80"
        expose:
            - 80

networks:
    sia-network:
        external: true


#    docker network create --subnet=172.20.0.0/24 --ip-range=172.20.0.0/24 --gateway=172.20.0.1 sia-network
