slot_mandrill:
  api_key: xxxxx
  disable_delivery: true # useful for dev/test environment. Default value is 'false'
  # debug: passed to \Mandrill causing it to output curl requests. Useful to see output
  # from CLI script. Default value is 'false'
  debug: true
  default:
    sender: info@example.com
    sender_name: John Doe # Optionally define a sender name (from name)
    subaccount: Project # Optionally define a subaccount to use
  proxy:
    use: true # when you are behing a proxy. Default value is 'false'
    host: example.com
    port: 80
    user: john
    password: doe123
